config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :tools, only: [:new, :create, :index, :show, :destroy] do
    resources :bookings, only: [:new, :create]
  end
  resources :categories, only: [:show, :index]
  resources :bookings, only: [:index, :destroy]
  get "about_us", to: "pages#about_us", as: :about_us
  get "profile/:id", to: "profiles#show", as: :profile
  get "profile/:id/edit", to: "profiles#edit", as: :edit_profile
  patch "profile/:id", to: "profiles#update"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :tool
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tools
  has_one_attached :photo
end

app/models/tool.rb
class Tool < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tools
  has_many :bookings
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number, :photo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :tool_params, only: [:new, :create]

  def index
    @bookings = Booking.includes(:user)
  end

  def new
    @tool = Tool.find(params[:tool_id])
    @booking = Booking.new
  end

  def create
    @tool = Tool.find(params[:tool_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.tool = @tool
    if @booking.save
      redirect_to profile_path(current_user)
    else
      render :new, notice: "Booking was not successfully created, try again!"
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path, notice: "Booking deleted"
  end
end



private

def tool_params
  @tool = Tool.find(params[:tool_id])
end

def booking_params
  params.require(:booking).permit(:start_date, :end_date)
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @tools = Tool.where(category: @category)

    @markers = @tools.geocoded.map do |tool| 
      {
        lat: tool.latitude,
        lng: tool.longitude
      }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :about_us]
  def home
  end

  def about_us
    @marco = User.find_by(email: "marco@ttr.com")
    @moises = User.find_by(email: "moises@ttr.com")
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to profile_path(@user), notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :phone_number, :email, :photo)
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  def show
    @tool = Tool.find(params[:id])
  end

  def new
    @tool = Tool.new
  end

  def create

    @tool = Tool.new(tool_params)
    @tool.user = current_user
    if @tool.save
      redirect_to tool_path(@tool)
    else
      render :new, notice: "We couldn't add that tool, try again!"
    end
  end

  def destroy
    @tool = Tool.find(params[:id])
    if @tool.destroy
      redirect_to tool_path
    else
      render :new
    end
  end

  private

  def tool_params
    params.require(:tool).permit(:name, :description, :price, :address, :category_id, photos: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to profile_path(@user), notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :phone_number, :email, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="book">


  <%= link_to " <- Back to profile", profile_path(current_user), class: "btn btn-secondary btn-sm my-4 btn-pepe" %>
  <% @bookings.each do |booking| %>

    <div class="book-grid">
      <% if booking.user.present? %>
          <div class="booking-card">
              <%= cl_image_tag booking.tool.photos.first.key, height: 200, width: 150, crop: :fill %>
                  <div class="booking-text">
                      <p>Start: <%= booking.start_date %></p>
                      <p>End: <%= booking.end_date  %></p>
              <%= link_to "delete", booking_path(booking), data: { turbo_method: :delete }, class: "btn btn-danger btn-sm my-4" %>
                  </div>
          </div>
      <% end %>
    </div>

  <% end %>


</div>

app/views/bookings/new.html.erb
<div class="form-card">
  <h1>New booking</h1>
  <%= simple_form_for [@tool, @booking] do |f| %>
    <%= f.input :start_date, as: :string, placeholder: "please select a start date", input_html: { data: { controller: "datepicker" } }%>
    <%= f.input :end_date, as: :string, placeholder: "please select an end date", input_html: { data: { controller: "datepicker" } } %>
    <%= f.submit "book", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/categories/index.html.erb
<% @categories.each do |category| %>
  <div class="col-12 col-md-6 w-100 mx-auto">
    <div class="d-flex justify-content-center border p-5 w-50 mx-auto my-5 w-75 category-list">
        <div class="cat-bg-img" style="background-image: url(<%= cl_image_path category.photo.key, crop: :fill %>)"></div>
        <div class="overlay"></div>
        <div class="text-cat">
          <%= link_to category.name, category_path(category) %>
        </div>
    </div>
  </div>
<% end %>

app/views/categories/show.html.erb
<div class="category-container">

  <h2 class="text-center underline text-dark my-4"><%= @category.name %> tools:</h2>
  <div class="container-grid">
    <% @tools.each do |tool| %>
      <div class="cards rounded-3">
        <% if tool.photos.attached? %>
          <%= cl_image_tag tool.photos.first.key, height: 300, width: 400, crop: :fill, class: "rounded" %>
        <% end %>
        <div class="card-text">
          <p><%= link_to tool.name, tool_path(tool) %></p>
          <p class="text-dark">Owner: <%= link_to tool.user.first_name, profile_path(tool.user) %></p>
          <% if current_user == tool.user %>
            <%= link_to "Delete", tool_path(tool), data: { turbo_method: :delete }, class: "btn btn-outline-danger btn-sm my-1 text-dark" %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="d-flex justify-content-center my-4 map">
    <div style="width: 80%; height: 400px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAP_BOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToolyToolyRental</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Baskervville+SC&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <div class="container-principal"><%= yield %></div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/about_us.html.erb
<div class="profile-card">
  <div class="marco">
      <%= cl_image_tag @marco.photo.key, height: 300, width: 400, crop: :fill, class:"img-profile" %>
      <div class="marco-text">
          <h1><%= @marco.first_name %> <%= @marco.last_name %></h1>
          <p>Hi I'm Marco, an Argentine guy who traded his River Plate jersey for a GitHub profile. He's now debugging in Spanish, trading his empanadas for tapas, and dreaming of creating the next big fermentive app.</p>
      </div>
      <div class="icons-social-profile">
        <%= link_to "https://www.linkedin.com/in/marcodgarbini/", target: "_blank" do %>
          <i class="fa-brands fa-linkedin text-dark fs-5 px-3 mb-3"></i>
        <% end %>
        <%= link_to "https://github.com/mgd1992", target: "_blank" do %>
            <i class="fa-brands fa-github text-dark fs-5 px-3"></i>
        <% end %>
      </div>
  </div> 

  <div class="moises">
      <%= cl_image_tag @moises.photo.key, height: 300, width: 400, crop: :fill, class:"img-profile" %>
      <div class="moises-text">
          <h1><%= @moises.first_name %> <%= @moises.last_name %></h1>
          <p> Hi! I'm Moises, a creative web developer and digital designer with expertise  in crafting seamless user experiences, UI design, and multimedia. Proficient in Adobe CC and Figma, with a talent for branding and print media outreach.</p>
      </div>
      <div class="icons-social-profile">
        <%= link_to "https://www.linkedin.com/in/moisesvelasquezgonzalez/", target: "_blank" do %>
          <i class="fa-brands fa-linkedin text-dark fs-5 px-3 mb-3"></i>
        <% end %>
        <%= link_to "https://github.com/Moises-V5", target: "_blank" do %>
            <i class="fa-brands fa-github text-dark fs-5 px-3"></i>
        <% end %>
      </div>
  </div>

</div>

app/views/pages/home.html.erb
<div class="main-container">
  <div class="text-field">
    <p>Affordable, high-quality tool rentals for DIYers and pros. Find the right equipment for any project at <strong>Tooly Tooly Rental</strong> convenient and hassle-free!</p>

    <%= link_to "Rent Now!", categories_path, class: "btn-cta" %>


  </div>
</div>

app/views/profiles/edit.html.erb
<div class="container">
  <%= simple_form_for @user, url: profile_path(@user), method: :patch do |f| %>
    <div class="field">
      <%= f.input :first_name %>
    </div>

    <div class="field">
      <%= f.input :last_name %>
    </div>

    <div class="field">
      <%= f.input :email %>
    </div>

    <div class="field">
      <%= f.input :phone_number %>
    </div>

    <div class="field">
      <%= f.input :photo, as: :file %>
    </div>

    <div class="actions">
      <%= f.button :submit, "Save changes" %>
    </div>
  <% end %>
</div>

app/views/profiles/show.html.erb
<h2 class="text-center mt-5">My Profile</h2>

<div class="profile-container pt-4 mx-auto my-5">
    <% if @user.photo.attached? %>
        <%= cl_image_tag @user.photo.key, crop: :fill %>
    <% else %>
        <p>No profile photo available</p>
    <% end %>

    <div class="profile-name">
        <h3><%= @user.first_name %> <%= @user.last_name %></h3>
    </div>

    <div class="card-bottom pb-4">
        <div class="profile-info">
            <p class="icon-phone"><i class="fa-solid fa-phone"></i> <%= @user.phone_number %></p>
            <p class="icon-email pb-1"><i class="fa-regular fa-envelope"></i> <%= @user.email %></p>
            <% if current_user == @user %>
              <%= link_to "Update Profile", edit_profile_path(@user), class: "btn btn-outline-primary btn-sm my-3" %>
            <% end %>
        </div>
        <%= link_to "My bookings", bookings_path, class: "text-center btn btn-secondary rounded-3" %>
    </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
    <p>©2024 All rights reserved. Site designed and develop by Marco & Moisés</p>
    
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-tooly">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "TT-rental-web.png" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse nav-list text-end" id="navbarSupportedContent" when>
      <ul class="navbar-nav mt-3 text-end">
          <li class="nav-item active">
            <%= link_to "Rent a tool", categories_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "New Tool", new_tool_path, class: "nav-link" %>
          </li>
          <li class="nav-item-about">
            <%= link_to "About us", about_us_path, class: "nav-link text-end" %>
          </li>
          <li class="nav-item dropdown text-end">
          <% if user_signed_in?%>
            <%if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, crop: :fill, class: "avatar", data: { bs_toggle: "dropdown" }, id: "navbarDropdown" %>
            <% else %>
              <i class="fa-solid fa-user" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
            <% end %>
          <% else %>
            <i class="fa-solid fa-user" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
          <% end %>
            <div class="dropdown-menu dropdown-menu-end p-0 m-1 w-25" aria-labelledby="navbarDropdown" data-bs-popper="static">
            <% if user_signed_in?%>
              <%= link_to "Profile", profile_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            <% else %>
              <%= link_to "Log in", new_user_session_path, class: "dropdown-item" %>
            <% end %>
            </div>
          </li>
      </ul>
    </div>

  </div>
</div>

app/views/tools/new.html.erb
<div class="form-card">
<%= simple_form_for @tool do |f| %>
  <%= f.input :name, placeholder: "Full name"%>
  <%= f.input :description, placeholder: "Add a description of the tool"%>
  <%= f.input :price, placeholder: "€"%>
  <%= f.input :address, placeholder: "Full address"%>
  <%= f.association :category, collection: Category.all%>
  <%= f.input :photos, as: :file, input_html: { multiple: true }%>

  <%= f.submit "New tool", class: "btn btn-primary" %>
<% end %>
</div>

app/views/tools/show.html.erb
<div class="show-card-container">
  <% if @tool.photos.attached? %>
    <%= cl_image_tag @tool.photos.first.key, class: "object-fit-cover h-auto w-100" %>
  <% end %>
  <div class="text-container">
    <h1><%= @tool.name %></h1>
    <p><%= @tool.description %></p>
    <h5><%= @tool.price %>€</h5>
    <%= link_to "Rent", new_tool_booking_path(@tool), class: "text-center btn btn-outline-info" %>
  </div>
</div>